version: "3.9"
services:
  deno:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: deno
  vue-ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui