version: "3.9"
services:
  deno:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: deno
  3d-client:
    build: 
      context: ./3d-client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: 3d-client